name: tf-examples-gpu

channels:
  - nvidia
  - conda-forge
  - anaconda
  
dependencies:
  - python=3.8
  - jupyterlab=3
  - matplotlib=3.5.2
  - scikit-learn=1.0.2
  - tensorflow-gpu=2.4.1
  - cuda-nvcc
  - cudnn
  
variables:
  # set logging level for Tensorflow to minimize logging to the console
  TF_CPP_MIN_LOG_LEVEL: 3