name: tf-examples-cpu
  
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - matplotlib=3.5.2
  - scikit-learn=1.0.2 
  - tensorflow-cpu=2.8.1

variables:
  # set logging level for Tensorflow to minimize logging to the console
  TF_CPP_MIN_LOG_LEVEL: 3